# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from akasha.proto import akasha_pb2 as akasha__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in akasha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AkashaStub(object):
    """============================================================
    Akasha — The Universal Shared Memory Service

    Like the Akashic Records, this service provides a universal space
    where all knowledge, state, and events are inscribed and accessible.
    ============================================================

    -- Core CRUD Operations --
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/akasha.Akasha/Put',
                request_serializer=akasha__pb2.PutRequest.SerializeToString,
                response_deserializer=akasha__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/akasha.Akasha/Get',
                request_serializer=akasha__pb2.GetRequest.SerializeToString,
                response_deserializer=akasha__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/akasha.Akasha/Delete',
                request_serializer=akasha__pb2.DeleteRequest.SerializeToString,
                response_deserializer=akasha__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/akasha.Akasha/Query',
                request_serializer=akasha__pb2.QueryRequest.SerializeToString,
                response_deserializer=akasha__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ListPaths = channel.unary_unary(
                '/akasha.Akasha/ListPaths',
                request_serializer=akasha__pb2.ListPathsRequest.SerializeToString,
                response_deserializer=akasha__pb2.ListPathsResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/akasha.Akasha/Subscribe',
                request_serializer=akasha__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=akasha__pb2.Event.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/akasha.Akasha/RegisterAgent',
                request_serializer=akasha__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=akasha__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/akasha.Akasha/Heartbeat',
                request_serializer=akasha__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=akasha__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.DepositPheromone = channel.unary_unary(
                '/akasha.Akasha/DepositPheromone',
                request_serializer=akasha__pb2.DepositPheromoneRequest.SerializeToString,
                response_deserializer=akasha__pb2.DepositPheromoneResponse.FromString,
                _registered_method=True)
        self.SensePheromones = channel.unary_unary(
                '/akasha.Akasha/SensePheromones',
                request_serializer=akasha__pb2.SensePheromonesRequest.SerializeToString,
                response_deserializer=akasha__pb2.SensePheromonesResponse.FromString,
                _registered_method=True)
        self.NidraStatus = channel.unary_unary(
                '/akasha.Akasha/NidraStatus',
                request_serializer=akasha__pb2.NidraStatusRequest.SerializeToString,
                response_deserializer=akasha__pb2.NidraStatusResponse.FromString,
                _registered_method=True)
        self.ListMemoryLayers = channel.unary_unary(
                '/akasha.Akasha/ListMemoryLayers',
                request_serializer=akasha__pb2.ListMemoryLayersRequest.SerializeToString,
                response_deserializer=akasha__pb2.ListMemoryLayersResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/akasha.Akasha/GetMetrics',
                request_serializer=akasha__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=akasha__pb2.GetMetricsResponse.FromString,
                _registered_method=True)


class AkashaServicer(object):
    """============================================================
    Akasha — The Universal Shared Memory Service

    Like the Akashic Records, this service provides a universal space
    where all knowledge, state, and events are inscribed and accessible.
    ============================================================

    -- Core CRUD Operations --
    """

    def Put(self, request, context):
        """/ Write a record to the shared memory.
        / Creates a new record or updates an existing one (version bumped).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """/ Read a record by exact path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """/ Delete a record by exact path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """-- Query Operations --

        / Query records by glob pattern and optional tag filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPaths(self, request, context):
        """/ List all paths under a given prefix.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """-- Real-time Subscriptions --

        / Subscribe to events matching a glob pattern.
        / Returns a server-streaming response of events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """-- Agent Lifecycle --

        / Register an agent with Akasha. Automatically creates the agent's
        / state tree under agents/{agent_id}/.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """/ Send a heartbeat to keep the agent's registration alive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DepositPheromone(self, request, context):
        """-- Stigmergy (Pheromone System) --

        / Deposit a pheromone trail. If a pheromone already exists at the
        / same trail, it is reinforced (intensities sum).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SensePheromones(self, request, context):
        """/ Sense active pheromones matching a glob pattern.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NidraStatus(self, request, context):
        """-- Cognitive Fabric --

        / Get the last Nidra consolidation cycle status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemoryLayers(self, request, context):
        """/ Get record counts per memory layer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """-- System --

        / Get server metrics and status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AkashaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=akasha__pb2.PutRequest.FromString,
                    response_serializer=akasha__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=akasha__pb2.GetRequest.FromString,
                    response_serializer=akasha__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=akasha__pb2.DeleteRequest.FromString,
                    response_serializer=akasha__pb2.DeleteResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=akasha__pb2.QueryRequest.FromString,
                    response_serializer=akasha__pb2.QueryResponse.SerializeToString,
            ),
            'ListPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPaths,
                    request_deserializer=akasha__pb2.ListPathsRequest.FromString,
                    response_serializer=akasha__pb2.ListPathsResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=akasha__pb2.SubscribeRequest.FromString,
                    response_serializer=akasha__pb2.Event.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=akasha__pb2.RegisterAgentRequest.FromString,
                    response_serializer=akasha__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=akasha__pb2.HeartbeatRequest.FromString,
                    response_serializer=akasha__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DepositPheromone': grpc.unary_unary_rpc_method_handler(
                    servicer.DepositPheromone,
                    request_deserializer=akasha__pb2.DepositPheromoneRequest.FromString,
                    response_serializer=akasha__pb2.DepositPheromoneResponse.SerializeToString,
            ),
            'SensePheromones': grpc.unary_unary_rpc_method_handler(
                    servicer.SensePheromones,
                    request_deserializer=akasha__pb2.SensePheromonesRequest.FromString,
                    response_serializer=akasha__pb2.SensePheromonesResponse.SerializeToString,
            ),
            'NidraStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.NidraStatus,
                    request_deserializer=akasha__pb2.NidraStatusRequest.FromString,
                    response_serializer=akasha__pb2.NidraStatusResponse.SerializeToString,
            ),
            'ListMemoryLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemoryLayers,
                    request_deserializer=akasha__pb2.ListMemoryLayersRequest.FromString,
                    response_serializer=akasha__pb2.ListMemoryLayersResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=akasha__pb2.GetMetricsRequest.FromString,
                    response_serializer=akasha__pb2.GetMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akasha.Akasha', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akasha.Akasha', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Akasha(object):
    """============================================================
    Akasha — The Universal Shared Memory Service

    Like the Akashic Records, this service provides a universal space
    where all knowledge, state, and events are inscribed and accessible.
    ============================================================

    -- Core CRUD Operations --
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/Put',
            akasha__pb2.PutRequest.SerializeToString,
            akasha__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/Get',
            akasha__pb2.GetRequest.SerializeToString,
            akasha__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/Delete',
            akasha__pb2.DeleteRequest.SerializeToString,
            akasha__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/Query',
            akasha__pb2.QueryRequest.SerializeToString,
            akasha__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/ListPaths',
            akasha__pb2.ListPathsRequest.SerializeToString,
            akasha__pb2.ListPathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/akasha.Akasha/Subscribe',
            akasha__pb2.SubscribeRequest.SerializeToString,
            akasha__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/RegisterAgent',
            akasha__pb2.RegisterAgentRequest.SerializeToString,
            akasha__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/Heartbeat',
            akasha__pb2.HeartbeatRequest.SerializeToString,
            akasha__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DepositPheromone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/DepositPheromone',
            akasha__pb2.DepositPheromoneRequest.SerializeToString,
            akasha__pb2.DepositPheromoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SensePheromones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/SensePheromones',
            akasha__pb2.SensePheromonesRequest.SerializeToString,
            akasha__pb2.SensePheromonesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NidraStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/NidraStatus',
            akasha__pb2.NidraStatusRequest.SerializeToString,
            akasha__pb2.NidraStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemoryLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/ListMemoryLayers',
            akasha__pb2.ListMemoryLayersRequest.SerializeToString,
            akasha__pb2.ListMemoryLayersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akasha.Akasha/GetMetrics',
            akasha__pb2.GetMetricsRequest.SerializeToString,
            akasha__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
